server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: map-service
          uri: lb://MAP-SERVICE
          predicates:
            - Path=/map-service/**

management:
  endpoints:
    web:
      exposure:
        include: 'gateway'
  endpoint:
    gateway:
      enabled: true # default: true