server:
  port: 9000

spring:
  application:
    name: user-service # service name
  # if spring.jpa.database is not set:
  # Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
  jpa:
    database: mysql

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3306/user_service
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    # if password is not 8+ long with combination of upper/lower/digit/special characters:
    # Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
    password: ### your password
    jpa:
      open-in-view: false
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create # SHOULD BE none for production

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

secret:
  jwt: ### your secret