server:
  port: 9002

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  application:
    name: review_service

  datasource:
    password: #pw
    driver-class-name: org.mariadb.jdbc.Driver
    username: #user
    url: jdbc:mariadb://localhost:3306/review_service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

