server:
  port: 9002

spring:
  profiles:
    include:
      - aws

  jpa:
    hibernate:
      ddl-auto: none # MUST SET none WHEN ON PRODUCTION STAGE
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  application:
    name: review-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: # RDS USERNAME
    password: # RDS PASSWORD
    url: # RDS ENDPOINT

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

